version: '3.1'
services:
  app:
    container_name: Blogpost_container
    image: blogpost:latest
    ports:
      - "8080:8080"
    restart: "no"
    depends_on:
      - postgresDB

  postgresDB:
    image: postgres
    ports:
      - '5432'

    environment:
      - POSTGRES_PASSWORD=root@1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Blogpost
    volumes:
      - data/da